name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.3, 7.4, 8.0 ]
        laravel: [ 7.*, 8.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 7.*
            testbench: 5.*

          - laravel: 8.*
            testbench: 6.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer self-update
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        if: ${{ always() }}
        run: vendor/bin/phpunit --log-junit ./tests.xml

      - name: Install Livewire V1
        if: ${{ always() }}
        run: |
          composer require "livewire/livewire:^1" --no-interaction

      - name: Execute tests
        if: ${{ always() }}
        run: vendor/bin/phpunit --log-junit ./tests_livewire1.xml

      - name: Install Livewire V2
        if: ${{ always() }}
        run: |
          composer require "livewire/livewire:^2" --no-interaction

      - name: Execute tests
        if: ${{ always() }}
        run: vendor/bin/phpunit --log-junit ./tests_livewire2.xml

      - name: Report test results to pull request
        if: ${{ always() }}
        uses: davidwessman/blinka_action@v1.1.4
        with:
          tag: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
          filename: ./tests.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report test results to pull request - Livewire V1
        if: ${{ always() }}
        uses: davidwessman/blinka_action@v1.1.4
        with:
          tag: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} Livewire V1
          filename: ./tests_livewire1.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report test results to pull request - Livewire V2
        if: ${{ always() }}
        uses: davidwessman/blinka_action@v1.1.4
        with:
          tag: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} Livewire V2
          filename: ./tests_livewire2.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
